import type { AspectRatio } from "@/types";
import type { TemplateCatalogItem, TemplateCategory } from "./catalog";

const GRADIENTS = [
  "gradient-1",
  "gradient-2",
  "gradient-3",
  "gradient-4",
  "gradient-5",
] as const;

type OfficialEntry = {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  compositionId: string;
  aspectRatio: AspectRatio;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
  popular?: boolean;
  premium?: boolean;
  remotionSlug: string;
};

/** Metadata aligned with https://www.remotion.dev/templates */
const OFFICIAL_ENTRIES: OfficialEntry[] = [
  {
    id: "remotion-blank",
    name: "Blank",
    description: "Nothing except an empty canvas",
    category: "Official",
    compositionId: "RemotionBlank",
    aspectRatio: "16:9",
    durationInFrames: 90,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "blank",
  },
  {
    id: "remotion-hello-world",
    name: "Hello World",
    description: "A playground with a simple animation",
    category: "Official",
    compositionId: "HelloWorld",
    aspectRatio: "16:9",
    durationInFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    popular: true,
    remotionSlug: "hello-world",
  },
  {
    id: "remotion-nextjs",
    name: "Next.js SaaS",
    description: "SaaS template for video generation apps",
    category: "Starter",
    compositionId: "NextJsSaaS",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    popular: true,
    remotionSlug: "next",
  },
  {
    id: "remotion-nextjs-vercel",
    name: "Next.js (Vercel Sandbox)",
    description: "Render videos on-demand using Vercel Sandbox",
    category: "Starter",
    compositionId: "NextJsVercelSandbox",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "vercel-sandbox",
  },
  {
    id: "remotion-nextjs-no-tailwind",
    name: "Next.js (No Tailwind)",
    description: "SaaS template without Tailwind CSS",
    category: "Starter",
    compositionId: "NextJsNoTailwind",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "next-no-tailwind",
  },
  {
    id: "remotion-nextjs-pages",
    name: "Next.js (Pages dir)",
    description: "SaaS template using the Pages router",
    category: "Starter",
    compositionId: "NextJsPages",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "next-pages-dir",
  },
  {
    id: "remotion-recorder",
    name: "Recorder",
    description: "A video production tool built entirely in JavaScript",
    category: "Creative",
    compositionId: "Recorder",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "recorder",
  },
  {
    id: "remotion-prompt-motion",
    name: "Prompt to Motion Graphics",
    description: "SaaS starter for AI-powered animation generation",
    category: "Starter",
    compositionId: "PromptMotionGraphics",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "prompt-to-motion-graphics",
  },
  {
    id: "remotion-javascript",
    name: "JavaScript",
    description: "The default starter template in plain JS",
    category: "Official",
    compositionId: "JavaScriptStarter",
    aspectRatio: "16:9",
    durationInFrames: 120,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "javascript",
  },
  {
    id: "remotion-render-server",
    name: "Render Server (Express.js)",
    description: "Express.js server for rendering videos with Remotion",
    category: "Starter",
    compositionId: "RenderServer",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "render-server",
  },
  {
    id: "remotion-electron",
    name: "Electron",
    description: "Render Remotion videos from a desktop app",
    category: "Starter",
    compositionId: "ElectronApp",
    aspectRatio: "16:9",
    durationInFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "electron",
  },
  {
    id: "remotion-react-router",
    name: "React Router 7",
    description: "SaaS template for video generation apps",
    category: "Starter",
    compositionId: "ReactRouter7",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "react-router",
  },
  {
    id: "remotion-3d",
    name: "3D",
    description: "Remotion + React Three Fiber starter template",
    category: "Creative",
    compositionId: "RemotionThreeD",
    aspectRatio: "16:9",
    durationInFrames: 120,
    fps: 30,
    width: 1920,
    height: 1080,
    popular: true,
    remotionSlug: "three",
  },
  {
    id: "remotion-stills",
    name: "Stills",
    description: "Dynamic PNG/JPEG template with built-in server",
    category: "Creative",
    compositionId: "Stills",
    aspectRatio: "16:9",
    durationInFrames: 30,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "stills",
  },
  {
    id: "remotion-audiogram",
    name: "Audiogram",
    description: "Text and waveform visualization for podcasts",
    category: "Podcast",
    compositionId: "Audiogram",
    aspectRatio: "1:1",
    durationInFrames: 180,
    fps: 30,
    width: 1080,
    height: 1080,
    popular: true,
    remotionSlug: "audiogram",
  },
  {
    id: "remotion-music-viz",
    name: "Music Visualization",
    description: "Text and waveform visualization for music",
    category: "Creative",
    compositionId: "MusicVisualization",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "music-visualization",
  },
  {
    id: "remotion-prompt-video",
    name: "Prompt to Video",
    description: "Create a story with images and voiceover from a prompt",
    category: "Creative",
    compositionId: "PromptToVideo",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "prompt-to-video",
  },
  {
    id: "remotion-skia",
    name: "Skia",
    description: "React Native Skia starter",
    category: "Creative",
    compositionId: "SkiaDemo",
    aspectRatio: "16:9",
    durationInFrames: 120,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "skia",
  },
  {
    id: "remotion-overlay",
    name: "Overlay",
    description: "Overlays for video editing software",
    category: "Creative",
    compositionId: "Overlay",
    aspectRatio: "16:9",
    durationInFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "overlay",
  },
  {
    id: "remotion-code-hike",
    name: "Code Hike",
    description: "Beautiful code animations",
    category: "Creative",
    compositionId: "CodeHike",
    aspectRatio: "16:9",
    durationInFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "code-hike",
  },
  {
    id: "remotion-stargazer",
    name: "Stargazer",
    description: "Celebrate your repo stars with a video",
    category: "Creative",
    compositionId: "Stargazer",
    aspectRatio: "16:9",
    durationInFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    remotionSlug: "stargazer",
  },
  {
    id: "remotion-tiktok",
    name: "TikTok Captions",
    description: "Generate animated word-by-word captions",
    category: "Social",
    compositionId: "TikTokCaptions",
    aspectRatio: "9:16",
    durationInFrames: 150,
    fps: 30,
    width: 1080,
    height: 1920,
    popular: true,
    remotionSlug: "tiktok",
  },
  {
    id: "remotion-editor-starter",
    name: "Editor Starter",
    description: "A boilerplate for starting your own video editor",
    category: "Starter",
    compositionId: "EditorStarter",
    aspectRatio: "16:9",
    durationInFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    premium: true,
    remotionSlug: "editor-starter",
  },
  {
    id: "remotion-watercolor-map",
    name: "Watercolor Map",
    description: "A beautiful 2D map for travel videos",
    category: "Creative",
    compositionId: "WatercolorMap",
    aspectRatio: "16:9",
    durationInFrames: 180,
    fps: 30,
    width: 1920,
    height: 1080,
    premium: true,
    remotionSlug: "watercolor-map",
  },
];

/** Official Remotion templates — https://www.remotion.dev/templates */
export const REMOTION_OFFICIAL_CATALOG: TemplateCatalogItem[] = OFFICIAL_ENTRIES.map(
  (entry, i) => ({
    ...entry,
    thumbnail: GRADIENTS[i % GRADIENTS.length],
    useCases: ["manual"] as TemplateCatalogItem["useCases"],
    official: true,
    remotionUrl: `https://www.remotion.dev/templates/${entry.remotionSlug}`,
  })
);

/** Composition dimensions for all official demos. */
export const REMOTION_OFFICIAL_DIMS: Record<
  string,
  {
    width: number;
    height: number;
    fps: number;
    durationInFrames: number;
    aspectRatio: AspectRatio;
  }
> = Object.fromEntries(
  OFFICIAL_ENTRIES.map((e) => [
    e.compositionId,
    {
      width: e.width,
      height: e.height,
      fps: e.fps,
      durationInFrames: e.durationInFrames,
      aspectRatio: e.aspectRatio,
    },
  ])
);
